import './globals.css'
import { Cairo_Play } from 'next/font/google'

const berk = Cairo_Play(
  { subsets: ['latin'],
  weight: ['400'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={berk.className}>
        <h1>this is a layout component</h1>
        {children}
        </body>
    </html>
  )
}
